### PR TITLE
Update gluon

### PR DESCRIPTION
**Pull request by MAFLO321**
# Changes
- **add:** support for all stable targets
- **add:** support for several usb devices
- **fix:** always hide the fastd key in wizard
## TODO
- [x] update build dependencies at [ffrgb website](https://regensburg.freifunk.net/technik/firmware-bauen/) to `sudo apt-get install git subversion python build-essential gawk unzip libncurses5-dev zlib1g-dev libssl-dev` [(ref)](http://gluon.readthedocs.org/en/v2016.1.3/user/getting_started.html)
- [x] update device list at [ffrgb website](https://regensburg.freifunk.net/mitmachen/router-aufstellen/)
- [ ] update [`gluon-packages`](https://github.com/ffrgb/gluon-packages), cherry-pick [this commit](https://github.com/freifunkMUC/gluon-packages/commit/d4d5aa3e3874ca6099e91fd70008ad5d54038169)
#### runtime-tested:
- ar71xx-generic (TP-Link TL-WR841N v10)
#### compile-tested only:
- ar71xx-nand
- mpc85xx-generic
- x86-64
- x86-generic
- x86-kvm_guest
- x86-xen_domu
## References

http://gluon.readthedocs.org/en/v2016.1.3/releases/v2016.1.html
https://github.com/freifunkMUC/site-ffm

### CODE REVIEW

**Comment by xf-** [comment]
Hi,

merge is up to @lephisto 
Device list is auto generated, based on stable files for download. A JSON maps for nicer names. Currently are only .bin listed and no tar-gz for VMs.

**Comment by MAFLO321** [comment]
Ok, thanks for reply.
I updated PR-comment.

**Comment by xf-** [comment]
You are in IRC or in binary kitchen?
Helping hands alwyas welcome :)

**Comment by MAFLO321** [comment]
Sorry, to far away from BinaryKitchen.
search for freifunk-waldblume on ffrgb map  :grin:

**Comment by lephisto** [comment]
Can you maybe join irc.hackint.org, so we can coordinate further development?

**Comment by lephisto** [comment]
Collected errors:
- opkg_install_cmd: Cannot install package gluon-respondd.
  make[6]: **\* [package_install] Error 255
  make[6]: Leaving directory `/home/bma/ffrgb/site-ffrgb/gluon-build/build/x86-xen_domu/openwrt'
  make[5]: *** [image] Error 2
  make[5]: Leaving directory`/home/bma/ffrgb/site-ffrgb/gluon-build/build/x86-xen_domu/openwrt'
  make[4]: **\* [image/GENERIC] Error 2
  make[4]: Leaving directory `/home/bma/ffrgb/site-ffrgb/gluon-build/build/x86-xen_domu/openwrt'
  make[3]: *** [call_image/GENERIC] Error 2
  make[3]: Leaving directory`/home/bma/ffrgb/site-ffrgb/gluon-build/build/x86-xen_domu/openwrt'
  make[2]: **\* [all] Error 2
  make[2]: Leaving directory `/home/bma/ffrgb/site-ffrgb/gluon-build'
  make[1]: *** [build] Error 2
  make[1]: Leaving directory`/home/bma/ffrgb/site-ffrgb'
  make: **\* [all] Error 2

what's missing? doesn't build well..

**Comment by MAFLO321** [comment]
I don't know i made a clean build and ther was no error.
Today I tried again on my Ubuntu 16.04 LTS x64.
Clean checkout of ffrgb experimental branch and I got now errors.
hmm.. 

Have you tried to re clone the repository ito a new empty directory ?

**Comment by lephisto** [comment]
Yes, tried. Build HOst is 14.04 LTS x64... still figuring out.

**Pull request merged**
